experiment:
  name: '#009 - ゼミ実験9回目'
  date: '2025-12-08T13:22:03.382632'
  researcher: AI Seminar Team
  purpose: 弁当箱検出AIの精度・速度比較実験
model:
  name: YOLOv3 + OpenCV
  framework: OpenCV DNN + YOLO
  version: '3.0'
  input_size:
  - 416
  - 416
  detection_modes:
  - opencv
  - yolo
  - hybrid
hyperparameters:
  confidence_threshold: 0.5
  nms_threshold: 0.4
  learning_rate: null
  batch_size: 1
dataset:
  name: Bento Box Dataset
  total_images: 0
  train_split: 0.0
  val_split: 0.0
  test_split: 1.0
  classes:
  - bento_box
  annotation_format: bbox
shooting_conditions:
  camera: Standard RGB Camera
  resolution: 640x480
  lighting: Indoor Fluorescent
  distance_cm: 30
  angle_degrees: 45
  background: Table Surface
evaluation_metrics:
  primary: average_error_mm
  secondary:
  - inference_time_ms
  - success_rate
  - confidence
  comparison_modes:
  - opencv
  - yolo
  - hybrid
environment:
  os: Windows/Linux
  python_version: 3.9+
  opencv_version: 4.8+
  gpu: Optional (CPU mode available)
output:
  logs_dir: ./outputs/logs
  visualizations_dir: ./outputs/visualizations
  metrics_csv: ./outputs/metrics.csv
  summary_json: ./outputs/evaluation_summary.json
remarks: 研究用3モード比較実験（CLI）
results:
  evaluation_date: '2025-12-08T13:22:13.568444'
  total_images_evaluated: 11
  modes:
    opencv:
      mode: opencv
      total_images: 11
      success_count: 11
      success_rate: 1.0
      avg_inference_time_ms: 3.9933161302046343
      avg_error_mm: 132.61236896539293
      std_error_mm: 54.259847085783704
      min_error_mm: 41.31448771822018
      max_error_mm: 201.7557420895713
      avg_confidence: 0.7000000000000001
    yolo:
      mode: yolo
      total_images: 11
      success_count: 10
      success_rate: 0.9090909090909091
      avg_inference_time_ms: 315.67209417169744
      avg_error_mm: 161.32968135921064
      std_error_mm: 267.54264413832715
      min_error_mm: 24.702186827054145
      max_error_mm: 999.0
      avg_confidence: 0.6124531030654907
    hybrid:
      mode: hybrid
      total_images: 11
      success_count: 10
      success_rate: 0.9090909090909091
      avg_inference_time_ms: 185.77831441705877
      avg_error_mm: 213.19522967885322
      std_error_mm: 254.4799883749394
      min_error_mm: 41.31448771822018
      max_error_mm: 999.0
      avg_confidence: 0.6124531030654907
