experiment:
  name: '#021 - ゼミ実験21回目'
  date: '2026-01-27T06:34:08.711218'
  researcher: AI Seminar Team
  purpose: 弁当箱検出AIの精度・速度比較実験
model:
  name: YOLOv3 + OpenCV
  framework: OpenCV DNN + YOLO
  version: '3.0'
  input_size:
  - 416
  - 416
  detection_modes:
  - opencv
  - yolo
  - hybrid
hyperparameters:
  confidence_threshold: 0.5
  nms_threshold: 0.4
  learning_rate: null
  batch_size: 1
dataset:
  name: Bento Box Dataset
  total_images: 0
  train_split: 0.0
  val_split: 0.0
  test_split: 1.0
  classes:
  - bento_box
  annotation_format: bbox
shooting_conditions:
  camera: Standard RGB Camera
  resolution: 640x480
  lighting: Indoor Fluorescent
  distance_cm: 30
  angle_degrees: 45
  background: Table Surface
evaluation_metrics:
  primary: average_error_mm
  secondary:
  - inference_time_ms
  - success_rate
  - confidence
  comparison_modes:
  - opencv
  - yolo
  - hybrid
environment:
  os: Windows/Linux
  python_version: 3.9+
  opencv_version: 4.8+
  gpu: Optional (CPU mode available)
output:
  logs_dir: ./outputs/logs
  visualizations_dir: ./outputs/visualizations
  metrics_csv: ./outputs/metrics.csv
  summary_json: ./outputs/evaluation_summary.json
remarks: 研究用3モード比較実験（CLI）
results:
  evaluation_date: '2026-01-27T06:34:20.341083'
  total_images_evaluated: 8
  modes:
    opencv:
      mode: opencv
      total_images: 8
      success_count: 8
      success_rate: 1.0
      avg_inference_time_ms: 2.6359260082244873
      avg_error_mm: 70.56492465196041
      std_error_mm: 47.45736543740503
      min_error_mm: 19.08493040809361
      max_error_mm: 118.4032855590226
      avg_confidence: 0.7
    yolo:
      mode: yolo
      total_images: 8
      success_count: 5
      success_rate: 0.625
      avg_inference_time_ms: 527.5394916534424
      avg_error_mm: 20.1187504904193
      std_error_mm: 3.4308237998603577
      min_error_mm: 15.961628155882428
      max_error_mm: 27.151856160368528
      avg_confidence: 0.5879444666206837
    hybrid:
      mode: hybrid
      total_images: 8
      success_count: 5
      success_rate: 0.625
      avg_inference_time_ms: 390.4719948768616
      avg_error_mm: 102.55368419630507
      std_error_mm: 85.7592363413862
      min_error_mm: 19.08493040809361
      max_error_mm: 215.81836782110915
      avg_confidence: 0.5670341665165306
