experiment:
  name: '#019 - ゼミ実験19回目'
  date: '2026-01-27T06:27:36.776719'
  researcher: AI Seminar Team
  purpose: 弁当箱検出AIの精度・速度比較実験
model:
  name: YOLOv3 + OpenCV
  framework: OpenCV DNN + YOLO
  version: '3.0'
  input_size:
  - 416
  - 416
  detection_modes:
  - opencv
  - yolo
  - hybrid
hyperparameters:
  confidence_threshold: 0.5
  nms_threshold: 0.4
  learning_rate: null
  batch_size: 1
dataset:
  name: Bento Box Dataset
  total_images: 0
  train_split: 0.0
  val_split: 0.0
  test_split: 1.0
  classes:
  - bento_box
  annotation_format: bbox
shooting_conditions:
  camera: Standard RGB Camera
  resolution: 640x480
  lighting: Indoor Fluorescent
  distance_cm: 30
  angle_degrees: 45
  background: Table Surface
evaluation_metrics:
  primary: average_error_mm
  secondary:
  - inference_time_ms
  - success_rate
  - confidence
  comparison_modes:
  - opencv
  - yolo
  - hybrid
environment:
  os: Windows/Linux
  python_version: 3.9+
  opencv_version: 4.8+
  gpu: Optional (CPU mode available)
output:
  logs_dir: ./outputs/logs
  visualizations_dir: ./outputs/visualizations
  metrics_csv: ./outputs/metrics.csv
  summary_json: ./outputs/evaluation_summary.json
remarks: 研究用3モード比較実験（CLI）
results:
  evaluation_date: '2026-01-27T06:28:20.714695'
  total_images_evaluated: 8
  modes:
    opencv:
      mode: opencv
      total_images: 8
      success_count: 8
      success_rate: 1.0
      avg_inference_time_ms: 13.636976480484009
      avg_error_mm: 164.3460361192783
      std_error_mm: 69.73769548046192
      min_error_mm: 9.69955975045923
      max_error_mm: 205.44061793966782
      avg_confidence: 0.8846011663021972
    yolo:
      mode: yolo
      total_images: 8
      success_count: 5
      success_rate: 0.625
      avg_inference_time_ms: 2836.1981213092804
      avg_error_mm: 19.314293820403268
      std_error_mm: 4.082846009464655
      min_error_mm: 14.258190387997457
      max_error_mm: 27.151856160368528
      avg_confidence: 0.5879444666206837
    hybrid:
      mode: hybrid
      total_images: 8
      success_count: 7
      success_rate: 0.875
      avg_inference_time_ms: 1543.6089634895325
      avg_error_mm: 75.05841225134311
      std_error_mm: 91.14773913176019
      min_error_mm: 9.682531000576299
      max_error_mm: 205.44061793966782
      avg_confidence: 0.6840252014538144
