experiment:
  name: '#020 - ゼミ実験20回目'
  date: '2026-01-27T06:30:45.953651'
  researcher: AI Seminar Team
  purpose: 弁当箱検出AIの精度・速度比較実験
model:
  name: YOLOv3 + OpenCV
  framework: OpenCV DNN + YOLO
  version: '3.0'
  input_size:
  - 416
  - 416
  detection_modes:
  - opencv
  - yolo
  - hybrid
hyperparameters:
  confidence_threshold: 0.5
  nms_threshold: 0.4
  learning_rate: null
  batch_size: 1
dataset:
  name: Bento Box Dataset
  total_images: 0
  train_split: 0.0
  val_split: 0.0
  test_split: 1.0
  classes:
  - bento_box
  annotation_format: bbox
shooting_conditions:
  camera: Standard RGB Camera
  resolution: 640x480
  lighting: Indoor Fluorescent
  distance_cm: 30
  angle_degrees: 45
  background: Table Surface
evaluation_metrics:
  primary: average_error_mm
  secondary:
  - inference_time_ms
  - success_rate
  - confidence
  comparison_modes:
  - opencv
  - yolo
  - hybrid
environment:
  os: Windows/Linux
  python_version: 3.9+
  opencv_version: 4.8+
  gpu: Optional (CPU mode available)
output:
  logs_dir: ./outputs/logs
  visualizations_dir: ./outputs/visualizations
  metrics_csv: ./outputs/metrics.csv
  summary_json: ./outputs/evaluation_summary.json
remarks: 研究用3モード比較実験（CLI）
results:
  evaluation_date: '2026-01-27T06:30:56.716594'
  total_images_evaluated: 8
  modes:
    opencv:
      mode: opencv
      total_images: 8
      success_count: 8
      success_rate: 1.0
      avg_inference_time_ms: 2.217531204223633
      avg_error_mm: 70.18799636600838
      std_error_mm: 47.28388619596743
      min_error_mm: 18.499478097988224
      max_error_mm: 117.82237000206582
      avg_confidence: 0.7
    yolo:
      mode: yolo
      total_images: 8
      success_count: 5
      success_rate: 0.625
      avg_inference_time_ms: 493.0283725261688
      avg_error_mm: 19.314293820403268
      std_error_mm: 4.082846009464655
      min_error_mm: 14.258190387997457
      max_error_mm: 27.151856160368528
      avg_confidence: 0.5879444666206837
    hybrid:
      mode: hybrid
      total_images: 8
      success_count: 5
      success_rate: 0.625
      avg_inference_time_ms: 339.4935727119446
      avg_error_mm: 102.19623380376845
      std_error_mm: 85.5632227097747
      min_error_mm: 18.499478097988224
      max_error_mm: 215.22260441512938
      avg_confidence: 0.5670341665165306
